workflows:
  react-native-android:
    name: My Scientific Calculator Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.x
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI & Build Web/Android
        script: |
          npx expo prebuild --platform android
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
